### ISSUE TITLE
Error when running on raspberry pi 4

### ISSUE THREAD

**Issue by rjheitman** [tmbates12/goes-dcs#1]
When i try to run on a pi4 it gives me this error
i checked and everything is up to date

pi@raspberrypi:~/goes-dcs $ python dcs.py test.lrit
  File "dcs.py", line 50
    def pseudo_decode(binary: bytes) -> str: # Discard the Parity Bit, it's just ASCII
                            ^
SyntaxError: invalid syntax

**Comment by unstablerobotgf** [comment]
If I remember correctly, python2 is still the default on Raspbian, so you'll have to install python3 and instead run the following: ``` python3 dcs.py test.lrit ```

**Comment by rjheitman** [comment]
Ok thank you i got it i updated to 3.8 from pythons website and it is running perfect now, thank you.
